### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [ggiamarchi/tftp-pilot#2]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary tftp-pilot -w /tmp/ext tftp-pilot==0.2.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting tftp-pilot==0.2.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/ca7/d72d96430ea72/tftp-pilot-0.2.0.tar.gz (3.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-apnjn3_n/tftp-pilot/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-apnjn3_n/tftp-pilot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-apnjn3_n/tftp-pilot/pip-egg-info
         cwd: /tmp/pip-wheel-apnjn3_n/tftp-pilot/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-apnjn3_n/tftp-pilot/setup.py", line 5, in <module>
        with open(path.join(here, "README.md"), encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-apnjn3_n/tftp-pilot/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
This doesn't occur with updated setuptools/pip from the repo but does occur on the released version.
